version: '3'
services:
    backend:
        build: ./backend
        ports: 
            - "5000:5000"
        restart: always
        environment: 
           SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://okteto:okteto@postgresql.otvmonteiro.svc.cluster.local/pcs3443?client_encoding=utf8
           JWT_SECRET_KEY: okteto
    backend:
        build: ./frontend
        ports: 
            - "3000:3000"
        restart: always