apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetolabsengsoftredes
spec:
  selector:
    matchLabels:
      app: projetolabsengsoftredes
  replicas: 1
  template:
    metadata:
      labels:
        app: projetolabsengsoftredes
    spec:
      containers:
      - name: projetolabsengsoftredes
        image: okteto.dev/projetolabsengsoftredes/backend
        ports:
        - containerPort: 5000