apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetolabsengsoftredes
spec:
  selector:
    matchLabels:
      app: projetolabsengsoftredes
  replicas: 1
  template:
    metadata:
      labels:
        app: projetolabsengsoftredes
    spec:
      containers:
      - name: backend
        image: okteto.dev/projetolabsengsoftredes-backend:latest
        ports:
        - containerPort: 5000
      - name: frontend
        image: okteto.dev/projetolabsengsoftredes-frontend:latest
        ports:
        - containerPort: 3000